import { Inter } from "next/font/google";
import Layout from "./components/templates/HomeLayout/HomeLayout";
import StyledComponentsRegistry from "@/lib/styled-components/registry";
import { GlobalStyles } from "./globalStyles";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "games app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStyles />
        <StyledComponentsRegistry>
          <Layout>{children}</Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
